In [2]:
import numpy as np

In [3]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)
arr*4

array([ 80, 108,  36,  48, 124,  68,  16, 200, 156, 140])

In [5]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

24.4
23.5
13.828955130450023


In [9]:
print(np.argmin(arr))
print(np.argmax(arr))

6
7


In [15]:
print(arr[6])
print(arr[7])

4
50


In [17]:
print(np.min(arr))
print(np.max(arr))
"They did give the same values"

4
50


In [18]:
new_arr = arr[arr > 20]
print(new_arr)

[27 31 50 39 35]


In [20]:
"3.2"
matrix = [
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
]
matrix = np.array(matrix)
print(np.shape(matrix)) # 3 rows and 4 columns
print(matrix[:, 2])
print(matrix[1, :])
print(matrix*2)

(3, 4)
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [26]:
print(np.mean(matrix[: 0]))
print(np.mean(matrix[: 1]))
print(np.mean(matrix[: 2]))
print(np.mean(matrix[: 3]))

print(np.mean(matrix[:, :]))

print(np.max(matrix[0, :]))
print(np.max(matrix[1, :]))
print(np.max(matrix[2, :]))

print(np.min(matrix[:, 0]))
print(np.min(matrix[:, 1]))
print(np.min(matrix[:, 2]))
print(np.min(matrix[:, 3]))

nan
10.75
11.125
11.5
11.5
17
21
19
5
12
14
3


In [33]:
flat_matrix = matrix.flatten()
print(np.argmax(flat_matrix))
print(np.argmin(flat_matrix))
# The matrix gets flattened into one row and 12 columns.

5
7


In [48]:
print(np.unravel_index(np.argmax(flat_matrix), (1, 12)))
print(np.unravel_index(np.argmin(flat_matrix), (1,12)))


(np.int64(0), np.int64(5))
(np.int64(0), np.int64(7))


In [47]:
new_matrix = matrix[matrix > 15]
print(new_matrix)
np.sort(new_matrix)

[17 21 19]


array([17, 19, 21])

In [49]:
"4"
arr = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])

def rows_with_primes(arr):
    def is_prime(n):
        if n < 2:
            return False
        for i in range(2, int(np.sqrt(n)) + 1):
            if n % i == 0:
                return False
        return True

    is_prime_vec = np.vectorize(is_prime)
    mask = np.any(is_prime_vec(arr), axis=1)
    return arr[mask]
print(rows_with_primes(arr))


[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [50]:
"5"
def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2, ::2] = 1  
    board[1::2, 1::2] = 1  
    return board
print(checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [68]:
def reverse_checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[1::2, ::2] = 1 
    board[::2, 1::2] = 1
    return board
print(reverse_checkerboard())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [69]:
"6"
def expand_universe(text, n):
    return (' ' * n).join(text)
expand_universe("galaxy", 3)

'g   a   l   a   x   y'

In [71]:
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
def secondDimmest(stars):
    sorted_rows = np.sort(stars, axis=1)
    return sorted_rows[:, -2]
print(secondDimmest(stars))

[1889 1647 1138 1863 1592]
